env:
  SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
  SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host myvultr
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
    - name: Sync files
      run: "rsync -avcz ${{ env.RSYNC_FLAGS }} ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.REMOTE_SOURCE }} ./"
      env:
        RSYNC_FLAGS: '--no-perms --no-owner --no-group --partial --times' #--dry-run
        SSH_HOST: myvultr
        REMOTE_SOURCE: "/root/rss/"
